version: "3.9"

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: bitrix_backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      - /app/node_modules  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health/bitrix"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: bitrix_webapp
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped